// Generated by CoffeeScript 1.7.1
var EventEmitter, Report, csv,
  __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

csv = require('csv');

EventEmitter = require('events').EventEmitter;

Report = (function(_super) {
  __extends(Report, _super);

  function Report() {
    return Report.__super__.constructor.apply(this, arguments);
  }

  Report.prototype.columns = [];

  Report.prototype.toCSV = function(outputStream) {
    var options, writer;
    options = {};
    if (this.columns.length) {
      options.columns = this.columns;
      options.header = true;
    }
    writer = csv().to.stream(outputStream, options);
    this.on('data', writer.write.bind(writer));
    this.on('end', writer.end.bind(writer));
    return this.run();
  };

  Report.prototype.run = function() {
    throw new Error("You must implement Report::run in your subclass");
  };

  return Report;

})(EventEmitter);

module.exports = Report;
